### ISSUE TITLE
See jstor in July 2018 Top 40 New Packages

### ISSUE THREAD

**Issue by stefaniebutland** [ropensci/jstor#69]
`jstor` was selected for RViews July 2018: Top 40 New Packages https://rviews.rstudio.com/2018/08/27/july-2018-top-40-new-packages/ 🎉

**Comment by tklebel** [comment]
Yay, that's amazing! 🎉  I might have stepped Joseph on his foot during a packed keynote at useR!, so I'm glad he still included the package 🤣 

Anyway, thanks for pointing this out (and tweeting about it) – I was not fully aware of R Views and especially not of this series of blog posts.
