### ISSUE TITLE
Vignette build failure: zip file 'part1.zip' cannot be opened

### ISSUE THREAD

**Issue by jeroen** [ropensci/jstor#80]
Vignette fails with `zip file 'part1.zip' cannot be opened`. Build log: https://dev.ropensci.org/job/jstor/lastBuild/console

```
# Writing 'articles/index.html'
# Reading 'vignettes/Introduction.Rmd'
# Writing 'articles/Introduction.html'
# Reading 'vignettes/analysing-n-grams.Rmd'
# Error : zip file 'part1.zip' cannot be opened
```

**Comment by tklebel** [comment]
The reason for this is that `part1.zip` is very large (> 1GB) and therefore not in the git repo. I always rendered the site locally and then pushed the files to GitHub. It seems that you are moving to having the page deployed off GitHub? 

Is there anything I could/should do to resolve this issue @jeroen ?

**Comment by tklebel** [comment]
As an aside: I have not been aware of https://dev.ropensci.org/blue/organizations/jenkins/jstor/activity, which is why I have not attempted to fix it... Somehow I missed this when it was introduced. Is there any mailing list I should be aware of where such things get communicated?

**Comment by jeroen** [comment]
The best solution is if you pre-compute your vignette. So rename your input vignette file to e.g `analysing-n-grams.Rmd.in` and then knit it on your local machine like so:

```r
library(knitr)
knit("vignettes/analysing-n-grams.Rmd.in", "vignettes/analysing-n-grams.Rmd")
```

That way the docs and cran vignettes get rendered from the Rmd that already has the output.

We don't have a mailing list, but we announced it on slack and in this blog post: https://ropensci.org/technotes/2019/06/07/ropensci-docs/

**Comment by tklebel** [comment]
Great, thank you! Also thanks for the blog post (https://ropensci.org/technotes/2019/12/08/precompute-vignettes/)! I'll try to fix it in the next 1-2 weeks.

Could you also invite the following email address to slack? t dot klebel at hotmail dot com

**Comment by jeroen** [comment]
Yes, will do!

**Comment by jeroen** [comment]
@maelle should have sent you an invite now :)

**Comment by tklebel** [comment]
Thanks @jeroen & @maelle!!
